In [2]:
import pandas as pd
df = pd.read_csv('/content/german_credit_data_updated.csv')
df.head()

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Credit Risk
0,0,67,male,2,own,NaN,little,1169,6,radio/TV,1
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,2
2,2,49,male,1,own,little,NaN,2096,12,education,1
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,1
4,4,53,male,2,free,little,little,4870,24,car,2

In [3]:
df.info()
print(df.describe())
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 954 entries, 0 to 953
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        954 non-null    int64
 1   Age               954 non-null    int64
 2   Sex               954 non-null    object
 3   Job               954 non-null    int64
 4   Housing           954 non-null    object
 5   Saving accounts   779 non-null    object
 6   Checking account  576 non-null    object
 7   Credit amount     954 non-null    int64
 8   Duration          954 non-null    int64
 9   Purpose           954 non-null    object
 10  Credit Risk       954 non-null    int64
dtypes: int64(6), object(5)
memory usage: 82.1+ KB
       Unnamed: 0         Age         Job  Credit amount    Duration  \
count  954.000000  954.000000  954.000000     954.000000  954.000000
mean   476.500000   35.501048    1.909853    3279.112159   20.780922
std    275.540378   11.379668    0.649681    2853.315158   12.046483
min      0.000000   19.000000    0.000000     250.000000    4.000000
25%    238.250000   27.000000    2.000000    1360.250000   12.000000
50%    476.500000   33.000000    2.000000    2302.500000   18.000000
75%    714.750000   42.000000    2.000000    3975.250000   24.000000
max    953.000000   75.000000    3.000000   18424.000000   72.000000

       Credit Risk
count   954.000000
mean      1.302935
std       0.459768
min       1.000000
25%       1.000000
50%       1.000000
75%       2.000000
max       2.000000

Unnamed: 0            0
Age                   0
Sex                   0
Job                   0
Housing               0
Saving accounts     175
Checking account    378
Credit amount         0
Duration              0
Purpose               0
Credit Risk           0
dtype: int64

In [4]:
df.drop(columns=['Unnamed: 0'], inplace=True)
df.columns

Index(['Age', 'Sex', 'Job', 'Housing', 'Saving accounts', 'Checking account',
       'Credit amount', 'Duration', 'Purpose', 'Credit Risk'],
      dtype='object')

In [5]:
df['Saving accounts'].fillna('No Saving', inplace=True)
df['Checking account'].fillna('No Checking', inplace=True)

/tmp/ipykernel_2306/1889667193.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Saving accounts'].fillna('No Saving', inplace=True)
/tmp/ipykernel_2306/1889667193.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Checking account'].fillna('No Checking', inplace=True)

In [6]:
df.isnull().sum()

Age                 0
Sex                 0
Job                 0
Housing             0
Saving accounts     0
Checking account    0
Credit amount       0
Duration            0
Purpose             0
Credit Risk         0
dtype: int64

In [7]:
df['Credit Risk'].value_counts()

Credit Risk
1    665
2    289
Name: count, dtype: int64

In [8]:
pd.crosstab(df['Checking account'], df['Credit Risk'])

Credit Risk         1    2
Checking account
No Checking       335   43
little            131  130
moderate          154  102
rich               45   14

In [9]:
df.groupby('Credit Risk')['Credit amount'].mean()

Credit Risk
1    2994.517293
2    3933.975779
Name: Credit amount, dtype: float64

In [10]:
df.groupby('Credit Risk')['Duration'].mean()

Credit Risk
1    19.139850
2    24.557093
Name: Duration, dtype: float64

In [11]:
df.groupby('Credit Risk')['Age'].mean()

Credit Risk
1    36.165414
2    33.972318
Name: Age, dtype: float64

In [12]:
pd.crosstab(df['Saving accounts'], df['Credit Risk'])

Credit Risk        1    2
Saving accounts
No Saving        143   32
little           367  209
moderate          63   33
quite rich        51    9
rich              41    6

In [13]:
pd.crosstab(df['Housing'], df['Credit Risk'])

Credit Risk    1    2
Housing
free          62   43
own          500  180
rent         103   66

In [14]:
pd.crosstab(df['Job'], df['Credit Risk'])

Credit Risk    1    2
Job
0             15    6
1            132   53
2            427  180
3             91   50

In [15]:
df.to_csv('cleaned_credit_data.csv', index=False)

In [16]:
from google.colab import files
files.download('cleaned_credit_data.csv')